import Product from './models/Product.js';
import Party from './models/Party.js';
import Bill from './models/Bill.js';
import Settings from './models/Settings.js';

export const seedInitialData = {
  settings: {
    businessName: 'Sri Lakshmi Jute & Gunny Mart',
    ownerName: 'S. Shanmugam',
    tagline: 'Wholesale & Retail Suppliers of All Kinds of Commercial Bags',
    logoText: 'SLJ',
    logoUrl: '',
    address: 'Shop No. 14, Commercial Market Yard, Opp. Old Cotton Market',
    city: 'Salem',
    state: 'Tamil Nadu',
    pincode: '636001',
    phone: '+91 98427 51234',
    email: 'sales@srilakshmijute.com',
    website: 'www.srilakshmijute.com',
    gstin: '33AABCS1429B1Z8',
    panNumber: 'AABCS1429B',
    bankName: 'State Bank of India',
    accountHolderName: 'Sri Lakshmi Jute & Gunny Mart',
    bankAccountNumber: '381920485910',
    bankIfsc: 'SBIN0001254',
    bankBranch: 'Salem Main Branch',
    upiId: 'lakshmijute@sbi',
    showBankDetailsOnInvoice: true,
    invoicePrefix: 'INV-',
    startingInvoiceNumber: 126,
    invoiceNumberPadding: 5,
    defaultTaxMode: 'CGST_SGST',
    defaultGstRate: 5,
    enableCgstSgst: true,
    enableIgst: true,
    defaultRcm: false,
    defaultPaymentStatus: 'Pending',
    activePaymentModes: ['Cash', 'UPI', 'Bank Transfer', 'Cheque'],
    defaultDueDays: 15,
    termsAndConditions: '1. Goods once sold will not be taken back or exchanged.\n2. Interest @ 18% per annum will be charged if payment is not received within 15 days.\n3. Subject to Salem jurisdiction only.',
    authorizedSignatoryName: 'S. Shanmugam',
    authorizedSignatoryDesignation: 'Proprietor',
    authorizedSignatoryText: 'Proprietor / Authorized Signatory',
    showSignatureSection: true,
    showBusinessLogo: true,
    showHsnSac: true,
    showGstBreakup: true,
    showTermsAndConditions: true,
    currency: 'INR (₹)',
    dateFormat: 'DD MMM YYYY',
    defaultUnit: 'Bag',
  },

  parties: [
    {
      name: 'ABC Traders',
      phone: '98765 43210',
      address: 'Plot 42, Industrial Area, Phase II, Erode',
      city: 'Erode',
      state: 'Tamil Nadu',
      gstin: '33AAACB2211C1Z4',
      creditLimit: 500000,
    },
    {
      name: 'Sri Venkatesh Stores',
      phone: '94432 87612',
      address: 'Bazaar Main Road, Near Bus Stand, Namakkal',
      city: 'Namakkal',
      state: 'Tamil Nadu',
      gstin: '33BBDVS9812A1Z9',
      creditLimit: 300000,
    },
    {
      name: 'Kumar Enterprises',
      phone: '97890 12345',
      address: 'Grain Market Yard, Shed No. 5, Tirupur',
      city: 'Tirupur',
      state: 'Tamil Nadu',
      gstin: '33CCKME4567D1Z2',
      creditLimit: 400000,
    },
    {
      name: 'Ramesh Agencies',
      phone: '98421 99887',
      address: 'Cotton Market Road, Rajapalayam',
      city: 'Rajapalayam',
      state: 'Tamil Nadu',
      gstin: '33DDRMA8901E1Z6',
      creditLimit: 250000,
    },
    {
      name: 'Global Traders',
      phone: '99440 33221',
      address: 'Export Hub, Harbour Bypass, Tuticorin',
      city: 'Tuticorin',
      state: 'Tamil Nadu',
      gstin: '33EEGTG3456F1Z3',
      creditLimit: 1000000,
    },
    {
      name: 'Balaji Agro Mart',
      phone: '94860 77112',
      address: 'Agro Yard, Pollachi Main Road, Coimbatore',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      gstin: '',
      creditLimit: 150000,
    },
  ],

  products: [
    {
      name: 'Gunny Bag',
      bagType: 'Gunny Bag',
      category: 'Gunny',
      defaultPrice: 28.00,
      rate: 28.00,
      hsnCode: '630510',
      hsnSac: '630510',
      gstRate: 5,
      description: 'B-Twill jute gunny sacks for grains, pulses and wheat packaging. 50kg capacity.',
      unit: 'Bag',
      stock: 4500,
      isArchived: false,
    },
    {
      name: 'Jute Bag',
      bagType: 'Jute Bag',
      category: 'Jute',
      defaultPrice: 35.00,
      rate: 35.00,
      hsnCode: '630510',
      hsnSac: '630510',
      gstRate: 5,
      description: 'Dense weave natural biodegradable jute sack for paddy, onions, and potatoes.',
      unit: 'Bag',
      stock: 2800,
      isArchived: false,
    },
    {
      name: 'PP Bag',
      bagType: 'PP Bag',
      category: 'PP',
      defaultPrice: 25.00,
      rate: 25.00,
      hsnCode: '392329',
      hsnSac: '392329',
      gstRate: 18,
      description: 'Polypropylene woven bag for animal feed, flour, rice, and fertilizers.',
      unit: 'Bag',
      stock: 8200,
      isArchived: false,
    },
    {
      name: 'HDPE Bag',
      bagType: 'HDPE Bag',
      category: 'HDPE',
      defaultPrice: 30.00,
      rate: 30.00,
      hsnCode: '392329',
      hsnSac: '392329',
      gstRate: 18,
      description: 'High-density polyethylene heavy industrial sacks for cement and chemical powders.',
      unit: 'Bag',
      stock: 3500,
      isArchived: false,
    },
    {
      name: 'Plastic Bag',
      bagType: 'Plastic Bag',
      category: 'Plastic',
      defaultPrice: 10.00,
      rate: 10.00,
      hsnCode: '392321',
      hsnSac: '392321',
      gstRate: 18,
      description: 'Virgin grade transparent LDPE/HM liner and packaging bags.',
      unit: 'Bag',
      stock: 6000,
      isArchived: false,
    },
    {
      name: 'Custom Bag',
      bagType: 'Custom Bag',
      category: 'Custom',
      defaultPrice: 42.00,
      rate: 42.00,
      hsnCode: '630590',
      hsnSac: '630590',
      gstRate: 12,
      description: 'Custom silk-screen or flexo printed bag with client wholesale branding.',
      unit: 'Bag',
      stock: 1500,
      isArchived: false,
    },
  ],

  bills: [
    {
      invoiceNumber: 'INV-00125',
      date: '2026-09-13',
      dueDate: '2026-09-28',
      partyName: 'ABC Traders',
      partyPhone: '98765 43210',
      partyAddress: 'Plot 42, Industrial Area, Phase II, Erode',
      partyGstin: '33AAACB2211C1Z4',
      items: [
        {
          productName: 'Gunny Bag',
          bagType: 'Gunny Bag',
          description: 'Standard Gunny Bag 50kg capacity',
          hsnCode: '630510',
          quantity: 1000,
          unit: 'Bags',
          pricePerBag: 28.095,
          rate: 28.095,
          discountPercent: 0,
          gstRate: 5,
          amount: 28095.24,
          discountAmount: 0,
          taxableAmount: 28095.24,
          cgstAmount: 702.38,
          sgstAmount: 702.38,
          igstAmount: 0,
          totalAmount: 29500,
        },
      ],
      subtotal: 28095.24,
      totalDiscount: 0,
      taxableAmount: 28095.24,
      taxMode: 'CGST_SGST',
      cgstTotal: 702.38,
      sgstTotal: 702.38,
      igstTotal: 0,
      totalTax: 1404.76,
      grandTotal: 29500,
      roundOff: 0,
      paidAmount: 29500,
      balanceAmount: 0,
      paymentStatus: 'Paid',
      paymentMode: 'Bank Transfer',
      notes: 'Dispatched via Express Cargo lorry service. E-way bill attached.',
      vehicleNumber: 'TN 33 AB 4590',
      createdAt: '2026-09-13T09:30:00Z',
    },
    {
      invoiceNumber: 'INV-00124',
      date: '2026-09-12',
      dueDate: '2026-09-27',
      partyName: 'Sri Venkatesh Stores',
      partyPhone: '94432 87612',
      partyAddress: 'Bazaar Main Road, Near Bus Stand, Namakkal',
      partyGstin: '33BBDVS9812A1Z9',
      items: [
        {
          productName: 'Jute Bag',
          bagType: 'Jute Bag',
          description: 'Heavy Duty Jute Bag 100kg',
          hsnCode: '630510',
          quantity: 500,
          unit: 'Bags',
          pricePerBag: 35.714,
          rate: 35.714,
          discountPercent: 0,
          gstRate: 5,
          amount: 17857.14,
          discountAmount: 0,
          taxableAmount: 17857.14,
          cgstAmount: 446.43,
          sgstAmount: 446.43,
          igstAmount: 0,
          totalAmount: 18750,
        },
      ],
      subtotal: 17857.14,
      totalDiscount: 0,
      taxableAmount: 17857.14,
      taxMode: 'CGST_SGST',
      cgstTotal: 446.43,
      sgstTotal: 446.43,
      igstTotal: 0,
      totalTax: 892.86,
      grandTotal: 18750,
      roundOff: 0,
      paidAmount: 0,
      balanceAmount: 18750,
      paymentStatus: 'Pending',
      paymentMode: 'Cash',
      notes: 'Credit term: 15 days. Payment expected on or before 27 Sep 2026.',
      vehicleNumber: 'TN 28 C 7714',
      createdAt: '2026-09-12T14:15:00Z',
    },
    {
      invoiceNumber: 'INV-00123',
      date: '2026-09-10',
      dueDate: '2026-09-25',
      partyName: 'Kumar Enterprises',
      partyPhone: '97890 12345',
      partyAddress: 'Grain Market Yard, Shed No. 5, Tirupur',
      partyGstin: '33CCKME4567D1Z2',
      items: [
        {
          productName: 'PP Bag',
          bagType: 'PP Bag',
          description: 'White PP Woven Bag 50kg',
          hsnCode: '392329',
          quantity: 1000,
          unit: 'Bags',
          pricePerBag: 14.50,
          rate: 14.50,
          discountPercent: 0,
          gstRate: 18,
          amount: 14500,
          discountAmount: 0,
          taxableAmount: 14500,
          cgstAmount: 1305,
          sgstAmount: 1305,
          igstAmount: 0,
          totalAmount: 17110,
        },
        {
          productName: 'HDPE Bag',
          bagType: 'HDPE Bag',
          description: 'HDPE Heavy Industrial Bag',
          hsnCode: '392329',
          quantity: 500,
          unit: 'Bags',
          pricePerBag: 22.00,
          rate: 22.00,
          discountPercent: 5,
          gstRate: 18,
          amount: 11000,
          discountAmount: 550,
          taxableAmount: 10450,
          cgstAmount: 940.50,
          sgstAmount: 940.50,
          igstAmount: 0,
          totalAmount: 12331,
        },
      ],
      subtotal: 25500,
      totalDiscount: 550,
      taxableAmount: 24950,
      taxMode: 'CGST_SGST',
      cgstTotal: 2245.50,
      sgstTotal: 2245.50,
      igstTotal: 0,
      totalTax: 4491,
      grandTotal: 29441,
      roundOff: 0,
      paidAmount: 29441,
      balanceAmount: 0,
      paymentStatus: 'Paid',
      paymentMode: 'Bank Transfer',
      notes: 'Paid in full via NEFT on 10 Sep 2026.',
      createdAt: '2026-09-10T11:00:00Z',
    },
    {
      invoiceNumber: 'INV-00122',
      date: '2026-09-08',
      dueDate: '2026-09-23',
      partyName: 'Ramesh Agencies',
      partyPhone: '98421 99887',
      partyAddress: 'Cotton Market Road, Rajapalayam',
      partyGstin: '33DDRMA8901E1Z6',
      items: [
        {
          productName: 'Gunny Bag',
          bagType: 'Gunny Bag',
          description: 'Gunny Bag Grade A',
          hsnCode: '630510',
          quantity: 500,
          unit: 'Bags',
          pricePerBag: 28.00,
          rate: 28.00,
          discountPercent: 0,
          gstRate: 5,
          amount: 14000,
          discountAmount: 0,
          taxableAmount: 14000,
          cgstAmount: 350,
          sgstAmount: 350,
          igstAmount: 0,
          totalAmount: 14700,
        },
        {
          productName: 'Custom Bag',
          bagType: 'Custom Bag',
          description: 'Custom Printed Bag with Red Logo',
          hsnCode: '630590',
          quantity: 300,
          unit: 'Bags',
          pricePerBag: 40.00,
          rate: 40.00,
          discountPercent: 0,
          gstRate: 12,
          amount: 12000,
          discountAmount: 0,
          taxableAmount: 12000,
          cgstAmount: 720,
          sgstAmount: 720,
          igstAmount: 0,
          totalAmount: 13440,
        },
      ],
      subtotal: 26000,
      totalDiscount: 0,
      taxableAmount: 26000,
      taxMode: 'CGST_SGST',
      cgstTotal: 1070,
      sgstTotal: 1070,
      igstTotal: 0,
      totalTax: 2140,
      grandTotal: 28140,
      roundOff: 0,
      paidAmount: 15000,
      balanceAmount: 13140,
      paymentStatus: 'Partial',
      paymentMode: 'Cash',
      notes: 'Advance of ₹15,000 received. Balance ₹13,140 pending.',
      createdAt: '2026-09-08T16:20:00Z',
    },
    {
      invoiceNumber: 'INV-00121',
      date: '2026-09-05',
      dueDate: '2026-09-20',
      partyName: 'Global Traders',
      partyPhone: '99440 33221',
      partyAddress: 'Export Hub, Harbour Bypass, Tuticorin',
      partyGstin: '33EEGTG3456F1Z3',
      items: [
        {
          productName: 'Jute Bag',
          bagType: 'Jute Bag',
          description: 'Heavy Jute Export Sacks',
          hsnCode: '630510',
          quantity: 2000,
          unit: 'Bags',
          pricePerBag: 36.00,
          rate: 36.00,
          discountPercent: 2,
          gstRate: 5,
          amount: 72000,
          discountAmount: 1440,
          taxableAmount: 70560,
          cgstAmount: 1764,
          sgstAmount: 1764,
          igstAmount: 0,
          totalAmount: 74088,
        },
      ],
      subtotal: 72000,
      totalDiscount: 1440,
      taxableAmount: 70560,
      taxMode: 'CGST_SGST',
      cgstTotal: 1764,
      sgstTotal: 1764,
      igstTotal: 0,
      totalTax: 3528,
      grandTotal: 74088,
      roundOff: 0,
      paidAmount: 74088,
      balanceAmount: 0,
      paymentStatus: 'Paid',
      paymentMode: 'Bank Transfer',
      notes: 'Full payment cleared via RTGS.',
      createdAt: '2026-09-05T10:00:00Z',
    },
    {
      invoiceNumber: 'INV-00120',
      date: '2026-09-02',
      dueDate: '2026-09-17',
      partyName: 'Balaji Agro Mart',
      partyPhone: '94860 77112',
      partyAddress: 'Agro Yard, Pollachi Main Road, Coimbatore',
      items: [
        {
          productName: 'PP Bag',
          bagType: 'PP Bag',
          description: 'PP Bags 25kg capacity',
          hsnCode: '392329',
          quantity: 1200,
          unit: 'Bags',
          pricePerBag: 14.00,
          rate: 14.00,
          discountPercent: 0,
          gstRate: 18,
          amount: 16800,
          discountAmount: 0,
          taxableAmount: 16800,
          cgstAmount: 1512,
          sgstAmount: 1512,
          igstAmount: 0,
          totalAmount: 19824,
        },
      ],
      subtotal: 16800,
      totalDiscount: 0,
      taxableAmount: 16800,
      taxMode: 'CGST_SGST',
      cgstTotal: 1512,
      sgstTotal: 1512,
      igstTotal: 0,
      totalTax: 3024,
      grandTotal: 19824,
      roundOff: 0,
      paidAmount: 19824,
      balanceAmount: 0,
      paymentStatus: 'Paid',
      paymentMode: 'Cash',
      createdAt: '2026-09-02T15:30:00Z',
    },
    {
      invoiceNumber: 'INV-00119',
      date: '2026-08-28',
      dueDate: '2026-09-12',
      partyName: 'ABC Traders',
      partyPhone: '98765 43210',
      partyAddress: 'Plot 42, Industrial Area, Phase II, Erode',
      partyGstin: '33AAACB2211C1Z4',
      items: [
        {
          productName: 'HDPE Bag',
          bagType: 'HDPE Bag',
          description: 'HDPE Sacks 50kg',
          hsnCode: '392329',
          quantity: 1000,
          unit: 'Bags',
          pricePerBag: 21.00,
          rate: 21.00,
          discountPercent: 0,
          gstRate: 18,
          amount: 21000,
          discountAmount: 0,
          taxableAmount: 21000,
          cgstAmount: 1890,
          sgstAmount: 1890,
          igstAmount: 0,
          totalAmount: 24780,
        },
      ],
      subtotal: 21000,
      totalDiscount: 0,
      taxableAmount: 21000,
      taxMode: 'CGST_SGST',
      cgstTotal: 1890,
      sgstTotal: 1890,
      igstTotal: 0,
      totalTax: 3780,
      grandTotal: 24780,
      roundOff: 0,
      paidAmount: 24780,
      balanceAmount: 0,
      paymentStatus: 'Paid',
      paymentMode: 'Cash',
      createdAt: '2026-08-28T11:45:00Z',
    },
  ],
};

export const seedDatabaseIfNeeded = async () => {
  try {
    // 1. Seed Settings if none exists
    const settingsCount = await Settings.countDocuments();
    if (settingsCount === 0) {
      await Settings.create(seedInitialData.settings);
      console.log('[Seed] Settings collection seeded with initial configuration');
    } else {
      // Ensure startingInvoiceNumber and prefix exist
      const existingSettings = await Settings.findOne();
      if (!existingSettings.startingInvoiceNumber) {
        existingSettings.startingInvoiceNumber = 126;
        existingSettings.invoicePrefix = 'INV-';
        await existingSettings.save();
      }
    }

    // 2. Seed Parties if none exists
    const partiesCount = await Party.countDocuments();
    if (partiesCount === 0) {
      await Party.insertMany(seedInitialData.parties);
      console.log(`[Seed] Seeded ${seedInitialData.parties.length} initial wholesale parties`);
    }

    // 3. Seed Products if none exists
    const productsCount = await Product.countDocuments();
    if (productsCount === 0) {
      await Product.insertMany(seedInitialData.products);
      console.log(`[Seed] Seeded ${seedInitialData.products.length} initial wholesale bag products`);
    }

    // 4. Seed Bills if none exists
    const billsCount = await Bill.countDocuments();
    if (billsCount === 0) {
      await Bill.insertMany(seedInitialData.bills);
      console.log(`[Seed] Seeded ${seedInitialData.bills.length} initial historical invoices`);
    }
  } catch (err) {
    console.error('[Seed] Error seeding database:', err.message);
  }
};
